controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true
  
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
  
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ['left_wheel']
    right_wheel_names: ['right_wheel']
    wheel_separation : 0.15
    wheel_radius : 0.035

    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 5.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 3.14
